theme: jekyll-theme-dinky
title: AHB3-Lite SoC Interconnect
description: Parameterised AHB3-Multi-layer Interconnect Switch
show_downloads: true
show_license: true
license: Non-Commercial License
github: [metadata]
